
language: generic

services:
  - docker

before_install:
  - docker build -t divya2304/docker-react-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true divya2304/docker-react-demo npm run test
