sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t MYIMAGE/docker-react-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true MYIMAGE/docker-react-demo npm run test
